firmware/src/gui/pages/module_view.hh
firmware/src/gui/pages/module_view_mapping_pane.hh
firmware/src/gui/pages/page_manager.hh
firmware/src/params/params_state.hh

When testing `latched.did_change()` the variable `latched` was a copy instead of a reference. So `did_change()` returned true every time after the first time

#350 Fix bug when mapping midi cc and panel knob to a single virtual knob

---

firmware/src/gui/pages/knobset_view.hh
firmware/src/patch_file/open_patch_manager.hh

Fixes #379 where knobmap scrolling order is based on the order the mappings were created. 
Now when a knob map is made, it is inserted into the knobset after the last inserted map for the same physical knob.
Also, when loading a patch, each knobset is sorted so all maps for the same physical knob are next to each other.

Update patch-serial (knobmap-order) #379

---

firmware/src/gui/elements/element_name.cc
firmware/src/gui/pages/module_view.hh
firmware/src/gui/pages/patch_selector.hh
firmware/src/gui/styles.hh

The bug is fixed by making sure there is a `' '` char after the closing `'^'` in the inline LVGL color command.   
Added text coloring functions that abstract away building raw colored strings

Fix: LVGL inline hex colors are occasionally rendered as text

---

firmware/src/CMakeLists.txt
firmware/src/core_m4/CMakeLists.txt
firmware/src/dynload/autoload_plugins.hh
firmware/src/gui/pages/main_menu.hh
firmware/src/gui/ui.hh
firmware/src/medium/debug_raw.h
firmware/system/new.cc
firmware/system/sbrk.cc
firmware/vcv_plugin/export/src/engine/Module.cpp

Fix memory leak in VCV Modules. The VCV wrapper was not cleaning up the non-smart pointer members of the rack::Module class
Also fixes a hang if no auto-loaded plugins were found

Fix memory leak

---

firmware/src/gui/pages/description_panel.hh
firmware/src/gui/pages/patch_selector.hh
firmware/src/gui/pages/save_dialog.hh
firmware/src/patch_file/open_patch_manager.hh

- Patches are reloaded from disk and then redrawn if the disk it was on was ejected and re-inserted and the patch is unmodified by MM. This was implemented previously but the patch was not being redrawn (only reloaded). https://forum.4ms.info/t/patch-autosaves/266/9
- Duplicating a patch over an existing patch that's been opened but no modifed, now works:
https://forum.4ms.info/t/firmware-update-did-not-update-patch/306
-  Patch filename and patch name (title) are now in sync. You cannot change the patch name from the "Info" button any longer (you can still edit the Patch Description of course). Changing the patch file name is done via Duplicate, which creates a new file. For now, if you wanted to rename and not make a copy then you have to go back to the old file to delete it. (Issue …

Patch file improvements

---

.github/workflows/build_test_firmware.yml
docs/firmware-building.md
docs/firmware-debugging.md
firmware/Makefile
firmware/cmake/log_levels.cmake
firmware/src/CMakeLists.txt
firmware/src/console/pr_dbg.hh

Adds a cmake setting to be used at compile time to specify the console log level (e.g. which of `pr_dbg()`, `pr_warn()`, etc are output to the UART console):
Default when using `make configure` is:
```
cmake --fresh --preset full -DLOG_LEVEL=DEBUG
``` 
Default when not specifying a level is NONE. This ensures CI-built releases will not have the console on by accident.
Documented in the README.

Debug console log level, CI uses gcc 12.3

---

firmware/vcv_plugin/export/src/VCV_module_wrapper.cc
firmware/vcv_plugin/export/src/engine/Module.cpp

Firmware was not calling all paths for setting a VCV Module's sample rate (the virtual function rack::Module::setSampleRate() was not being called. Though, rack engine's samplerate and the args passed to Module::process() were getting the latest sample rate). 
Fixing this fixed various bugs, including Plateau size parameter < 18% stopping the audio, and HetrickCV PhasorGen having a fast speed when not clocked externally.
There are probably other VCV-ported modules with issues that are now fixed.
This changes the API to v1.4 (since it adds the `rack::engine::Module::set_samplerate()` symbol)

Set VCV module sample rate properly

---

firmware/src/gui/helpers/roller_hover_text.hh
firmware/src/gui/pages/module_list.hh
firmware/src/gui/pages/module_view.hh
firmware/src/gui/pages/patch_selector.hh
simulator/Makefile

This PR helps with displaying text in rollers that's too wide for the roller by making the long text scroll horizontally. 
This effects the PatchSelector list of patches, ModuleView list of elements, ModuleList list of brands/modules. 
The way of doing this is to have a single-line label object that's positioned exactly over the selected roller item's position. This label is hidden when the roller is scrolled, loses focus, or is hidden, and then shown when the roller is done being redrawn.
As far as I could tell, there's no way to add a callback on an event for when the roller's inner label is no longer being scrolled/animated. So what I did here was hook a callback onto the roller's `LV_EVENT_DRAW_POST_END` event, and then check if the selected index has changed since the last time. A …

Scroll wide text items in rollers

---

firmware/src/gui/helpers/roller_hover_text.hh

Hover text moves to accomodate changes in roller size

Fix roller hover text drawn in the wrong place when creating a new cable

---

firmware/src/gui/pages/base.hh
firmware/src/gui/pages/cable_drawer.hh
firmware/src/gui/pages/patch_view.hh

LVGL internally uses img types for canvases, and the height variable has 11 bits -- so we are limited to 2047 pixels
Fixes #408

Fix cables not drawn past 6 rows of modules

---

firmware/CMakeLists.txt
firmware/src/fs/fs_messages.hh
firmware/src/fw_update/firmware_file_finder.hh
firmware/src/fw_update/hash/hash_processor.hh
firmware/src/patch_file/file_storage_comm.hh
firmware/system/startup_ca7.s
firmware/vcv_ports/glue/hetrickcv/CMakeLists.txt

Core 2 was calling a C function in its startup while its stack pointer was still in SYSRAM. At the same time, Core 1 is initializing data which sometimes may be in SYSRAM.
This fix makes Core 2 set its stack pointer to DDR RAM before executing any functions.
Also a few other minor fixes/cleanups:
- update mdrivlib (breaking change: renamed ICC type)
- Fixed cmake deleting the symbol list outside of its build tree on `make clean`
- silenced a warning
- updated plugin-sdk (added speex symbols)

Fix startup concurrency issue between A7 core 1 and core 2

---

firmware/src/gui/pages/patch_view.hh
firmware/src/patch_play/patch_player.hh

InterpDelay was setting a value for the phase outside of 0-1 if a delay time < 0 was set. This can happen when Size is very small and the LFO depth is high enough.
https://forum.4ms.info/t/plateau-built-in-mm-stops-audio-when-turning-size-smaller-than-9-oclock/431/5

Fix Plateau stopping audio when size is low

---

firmware/src/audio/audio.cc
firmware/src/core_m4/controls.cc
firmware/src/core_m4/controls.hh
firmware/src/core_m4/midi_controls.hh
firmware/src/gui/pages/add_map_popup.hh
firmware/src/gui/pages/system_info_tab.hh
firmware/src/medium/conf/control_conf.hh
firmware/src/wifi/detection.hh

- Pot ranges are hard-limited to the range 0..1 (previously it was possible to have the interpolator overshoot and get a small negative value).
- WiFi status displays more consistently on the Info settings page
- Add Map pop-up pane defaults the cursor to the "OK" button, and does not wrap.
- Fixed issue with multiple MIDI notes firing causing some gates to be lost

Various fixes: Pot ranges, midi gate, wifi status display

---

firmware/vcv_plugin/export/src/plugin/Plugin.cpp
firmware/vcv_ports/CMakeLists.txt
firmware/vcv_ports/glue/ext_plugin/ext_plugin_builtin.hh
firmware/vcv_ports/internal_plugin_manager.hh
simulator/CMakeLists.txt
simulator/ext-plugins.cmake
simulator/plugin.cmake
simulator/src/ext_plugin_builtin.hh.in
simulator/src/settings.hh

This adds a crude but simple way to run a plugin in the simulator.
There are two things to be done, which are also documented in the comments in `simulator/ext-plugins.cmake` file:
1. Add the path to the external plugin directory, and the name of the cmake target library to ext-plugins.cmake. For example, to run Venom in the simulator, you could add this to the top of `ext-plugins.cmake` (assuming the path is correct):
```cmake
list(APPEND ext_builtin_brand_paths "${CMAKE_CURRENT_LIST_DIR}/../../metamodule-plugin-examples/Venom")
list(APPEND ext_builtin_brand_libname "Venom")
```
2. Rename the `init(rack::Plugin*)` function to `init_Brand(rack::Plugin*)`. So for Venom, for example, it would be `init_Venom`. If you want to make it work for building as a Rack plugin, MM plugin, and MM …

Allow external plugins as built-ins in Simulator

---

firmware/src/fs/asset_drive/untar.cc
firmware/src/fs/fatfs/fat_file_io.hh
firmware/src/gui/pages/module_view_action_menu.hh

This came up with Venom, where presets are located in `presets/SUBDIR/*.vcvm`. 
Modified the preset loading to search for subdirs and cleaned up a few things.

Load Presets from subdirs

---

firmware/src/dynload/plugin_file_list.hh
firmware/src/dynload/plugin_file_scan.hh
firmware/src/dynload/plugin_loader.hh
firmware/src/gui/pages/main_menu.hh
firmware/src/gui/pages/plugin_tab.hh
firmware/src/patch_file/patch_fileio.hh

- Sort plugin names, and patch list alphabetically case-insensitive
- Hide plugins that can't be loaded by the current firmware
- Fix issue with max 32 mmplugin files being scanned
- Remove "wrapping" on main menu group (when the rotary selects the last time, continuing to turn the rotary does not wrap around to the first time anymore)

Lists cleanup

---

firmware/src/dynload/plugin_file_list.hh
firmware/src/dynload/plugin_file_scan.hh
firmware/src/dynload/plugin_loader.hh
firmware/src/gui/pages/main_menu.hh
firmware/src/gui/pages/plugin_tab.hh
firmware/src/patch_file/patch_fileio.hh

v2.x version of #444 
No wrapping on main menu
Increase max plugins to find
Warning if find more than max plugins
Update cpputil (less_ci)
Sort patch files and dirs case-insensitive
Only display plugins that can be hosted by firmware
Sort plugins by name, case-insensitive
Fix plugin names out of order in plugin tab

List cleanup (v2.x)

---

firmware/src/core_a7/aux_core_main.cc
firmware/src/core_a7/aux_core_player.hh
firmware/src/core_a7/smp_api.hh
firmware/src/patch_play/balance_modules.hh
firmware/src/patch_play/cable_cache.hh
firmware/src/patch_play/multicore_play.hh
firmware/src/patch_play/patch_player.hh
simulator/stubs/drivers/cycle_counter.hh

This allows the PatchPlayer to balance the cpu load of modules between both cores when playing a patch. It brings down the overall CPU load of large patches.
There are two aspects of it:
- Internal cables are processed by both cores instead of just by one. First, the output jacks of **all** of the core's modules are read and the values are written to a cable cache. Then for each module, the input jacks are populated from this common cache and the module is run. This has two advantages: 1) cable update takes 50% of the time (at best) since both cores operate in parallel, and 2) cable update happens closer to module update and on the same core, so we benefit from more cache hits. Both of these benefits depend on the details of the patch topology, but in practice I measured some substantial …

Load balancing of modules and internal cables

---

firmware/.clangd

DLD would sometimes start up with one channel (usually A) not clocking. This was due to the saved state having a default ping time of 0.
Also fixes an issue with the Ping LED not tracking an external ping very well.

Fix DLD clock issues

---

firmware/CMakeLists.txt
firmware/lib/fatfs/source/ff.h
firmware/src/CMakeLists.txt
firmware/src/core_a7/fs_proxy.hh
firmware/src/fs/dirent/dirent.cc
firmware/src/fs/fatfs/fat_file_io.hh
firmware/src/fs/fileio_t.hh
firmware/src/fs/syscall/filedesc_manager.cc
firmware/src/fs/syscall/filedesc_manager.hh
firmware/src/fs/syscall/filesystem.hh
firmware/src/fs/syscall/fs_syscall_proxy.cc
firmware/src/fs/syscall/fs_syscall_proxy.hh
firmware/src/fs/syscall/syscalls.cc
firmware/src/patch_file/patch_list_helper.hh
firmware/system/time.cc
firmware/system/time.hh
firmware/vcv_plugin/export/CMakeLists.txt
firmware/vcv_plugin/export/src/keep-symbols.cc
firmware/vcv_plugin/export/src/system.cc
simulator/CMakeLists.txt
simulator/src/ui.cc
simulator/stubs/drivers/time.cc
simulator/stubs/patch_file/file_storage_comm.hh

This adds support for the posix dirent.h functions:
opendir()
closedir()
readdir()
rewinddir()
These can be used to access the SD or USB drives.
The prefix `usb:/` designates the USB drive, and the prefix `sdc:/` designates the SD Card. `ram:/` is the Ramdisk, and `nor:/` is the internal NorFlash chip.
Without any prefix, the RAM disk is the default (plugin assets dirs)

Dirent functions: opendir(), closedir(), readdir(), etc.

---

firmware/src/gui/helpers/lv_helpers.hh
firmware/src/gui/pages/file_browser/file_save_dialog.hh
firmware/src/gui/pages/knobset_view.hh
firmware/src/gui/pages/module_list.hh
firmware/src/gui/pages/module_view_action_menu.hh
firmware/src/gui/pages/module_view_automap.hh
firmware/src/gui/pages/patch_selector.hh
firmware/src/gui/pages/patch_selector_sidebar.hh
firmware/src/gui/pages/patch_selector_subdir_panel.hh
firmware/src/gui/pages/plugin_tab.hh
firmware/src/gui/styles.hh
firmware/src/patch_file/open_patch_manager.hh
firmware/src/patch_file/open_patches.hh
firmware/src/patch_file/patch_dir_list.hh
firmware/src/patch_file/reload_patch.cc

Fixes a memory corruption error in the PatchSelector page that can cause a crash when opening lots (> 20) patches. It happens with increased frequency if the patches consume lots of memory (especially the GUI buffers for graphic screens).
The number of Recent patches is now reduced to 5, but in a future PR it'll become a user settings option.
There also is an unrelated crash happening when the PatchSelector page is displayed more than 32 times. It was infrequent but memory pressure increased the chance of it happening.

Fix crash in PatchSelector

---

firmware/src/CMakeLists.txt
firmware/src/patch_play/patch_player.hh
firmware/src/patch_play/plugin_module.cc
firmware/src/patch_play/plugin_module.hh
firmware/tests/Makefile
firmware/tests/stubs/plugin_module.cc
simulator/CMakeLists.txt

This allows the memory leak fixed in Bogaudio to work (and probably other rack plugin module cleanup functions to work properly)

Deinit plugin modules before removing (for Rack plugins, call onRemove)

---

firmware/src/gui/pages/page_manager.hh
firmware/src/gui/pages/prefs_tab.hh
firmware/src/gui/slsexport/prefs_pane_catchup.cc
firmware/src/gui/slsexport/prefs_pane_catchup.hh
firmware/src/gui/ui.hh
firmware/src/params/catchup_manager.hh
firmware/src/params/catchup_param.hh
firmware/src/patch_play/patch_player.hh
firmware/src/patch_play/patch_player_catchup.cc
firmware/src/patch_play/patch_playloader.hh
firmware/src/user_settings/catchup_settings.hh
firmware/src/user_settings/settings_parse.cc
firmware/src/user_settings/settings_serialize.cc
firmware/tests/settings_parse_tests.cc
simulator/src/ui.cc

See https://forum.4ms.info/t/track-when-equal-not-picking-up-with-push-module-buttons/1208
In track on equal mode, if the min/max of the mapping does not overlap the param's current value, then the knob can never be made to be equal. Therefore you cannot start tracking (aka "pickup") a param that's not already tracking. Therefore the param is stuck.
Two solutions are presented here and a user setting (`Allow jumping out-of-range params`) to select which one.
- Allow jumping off: Display a notification when you move the panel knob to the extreme that's closest to where the mapped param's value is.
- Allow jumping on: Automatically pickup (start tracking) the param when the knob is as close as it can be.

Track on Equal mode can notify user or jump an out-of-range value

---

firmware/src/conf/hsem_conf.hh
firmware/src/core_a7/hsem_handler.hh
firmware/src/core_a7/main.cc
firmware/src/dynload/dynloader.hh
firmware/tests/stubs/drivers/cache.hh

The problem was the instruction cache was not invalidated on both cores after loading the changed code segments. So  after loading new code into the data cache, the instruction cache on either core might still contain old instructions. This led to very strange crashes with seemingly impossible backtraces.

Fix crash when unloading a plugin, then loading a different version of same plugin

---

firmware/src/gui/pages/knobmap.hh
firmware/src/gui/pages/module_list.hh
firmware/src/gui/pages/plugin_popup.hh
firmware/src/load_test/test_modules.hh

- Module List was not handling the case when two plugins each have a distinct brand slug but have the same display name (e.g. Stellare Modular, and Stellare Modular Creative Suite)
- MIDI channel dropdown menu would not close if you pressed Back on the Edit Map page
- Plugin info pop-up contained the old working "autoload", which should be "pre-load"

Small fixes: Module List brand merging, minor GUI stuff

---

firmware/src/gui/elements/state_names.hh
firmware/src/gui/pages/manual_control_popup.hh
firmware/vcv_plugin/export/src/plugin/Model.cpp
firmware/vcv_plugin/internal/make_element.cc

This refactors PR #507 to maintain the size of the Elements variant, and to not add fields to Pot, but instead add fields to Knob since no other class derives from Knob.
Without this, native CoreModule plugins such as Airwindows would crash on load

Refactor snapped Knobs to maintain API consistancy

---

firmware/src/audio/midi.hh
firmware/src/core_a7/aux_core_player.hh
firmware/src/midi/midi_message.hh
firmware/vcv_plugin/export/src/midi_input_queue.cpp
firmware/vcv_plugin/export/src/midi_message.cc
firmware/vcv_ports/RackCore/MIDI_CV.cpp

Fixes Rack MIDI messages not always having their size set (would sometimes be 0 even if the message really was 3).
Also cleans up the History screen on the MIDI_CV module

Midi size fix

---

firmware/src/gui/elements/state_names.hh
firmware/src/gui/pages/manual_control_popup.hh
firmware/vcv_plugin/export/src/plugin/Model.cpp
firmware/vcv_plugin/internal/make_element.cc

This fixes another edge case in the API change. Airwindows could crash since it does not initialize the new fields.
Adding a new Element variant type fixes this because the fields won't be accessed unless the new variant index is set.
SDK Api bumped up to v2.0.3

Fix snapped knobs, part 2

---

firmware/lib/stm32-usb-host-lib/Core/Src/usbh_core.c
firmware/lib/stm32-usb-host-lib/Core/Src/usbh_ctlreq.c
firmware/src/usb/usb_host_helper.hh
firmware/src/usb/usbh_midi.cc
firmware/src/usb/usbh_midi_jacks.cc
firmware/src/usb/usbh_midi_jacks.hh
firmware/vcv_plugin/export/src/module_widget_adaptor.hh

This provides a fix for USB MIDI devices with vendor ID of Native Instruments, by not attempting to correct non-standard descriptor lengths. It also is more immune to crashing when encountering non-standard descriptors.
This also fixes a bug in the MM firmware that ignored MIDI from devices with large endpoint transfer sizes (>=256 bytes).

Fix MIDI for NI and other controllers

---

firmware/src/patch_play/auto_map.hh

Auto-map (New Knobset) gives the mapping an alias name equal to the parameter name. Since the knobset itself gets the name of the module, we don't need to show it in every mapping. Since "ParamName - ModuleName" is the default when no alias is set, the solution is to provide an alias of "ParamName" 
Nothing different is done for Auto-map All, since this action combines multiple modules into the name knobset.
This PR also makes auto-mapped jack mappings extend into the MetaAIO expander if it's detected as being connected.

Automap improvements

---

firmware/src/gui/pages/module_view.hh
firmware/vcv_plugin/export/src/make_element_names.hh
firmware/vcv_plugin/export/src/module_widget_adaptor.hh

This fixes the problem when using the VCV Rack adaptor layer, that if a widget is modified after the call to ModuleWidget::addParam()  (or addOutput, etc), then the changes won't be copied into the Element.
E.g. this:
```
addParam(knob);
knob->box.pos = Vec(20, 20);
addInput(triggerjack);
module->configInput(TRIG_JACK, "Trigger");
```
wouldn't set the box position correctly in the first case, or set the jack name correctly in the second case.
This PR fixes this issue by assigning the element fields after the ModuleWidget is finished being constructed. So, it still doesn't work to modify a widget's box size or associated name fields while the module is running.

Allow widgets to be changed after ModuleWidget::addOutput/addInput/addParam/addChild

---

firmware/CMakePresets.json
firmware/src/CMakeLists.txt
firmware/src/audio/audio.cc
firmware/src/core_a7/async_thread_control.cc
firmware/src/fs/helpers.cc
firmware/src/fs/helpers.hh
firmware/src/gui/module_menu/plugin_module_menu.hh
firmware/src/gui/pages/file_browser/file_browser.hh
firmware/src/gui/pages/file_browser/file_save_dialog.hh
firmware/src/patch_file/change_checker.hh
firmware/src/patch_file/reload_patch.cc
firmware/src/patch_play/patch_player.hh
firmware/vcv_plugin/export/src/app/ModuleWidget.cpp
firmware/vcv_plugin/export/src/module_widget_adaptor.hh
firmware/vcv_plugin/export/src/resampler.cc
simulator/plugin.cmake
simulator/src/audio_stream.hh
simulator/src/main.cc
simulator/src/settings.hh
simulator/src/ui.cc
simulator/src/ui.hh

Various issues cherry-picked from dev branches:
- Async thread pauses timers while executing. This fixes the issue with Async Threads never restarting or being locked sometimes if processing takes too long.
- SpeexResampler: fix stride typo
- Performance improvement for modules with graphics: Don't step() a module widget with no custom step()
- Process patch mod queue when patch is paused, allowing user to add or modify maps when patch is paused
- Simulator volume was too high -- now defaults to equating 5V with full-scale signal. You can adjust this with the `-l` option (run `simulator -h` to see help)
- File browser and save dialog can be triggered from audio context to be run in the GUI context
- Various other cleanups

Various improvements: AsyncThread, File Browser, Simulator audio level

---

firmware/src/gui/helpers/load_meter.hh
firmware/src/gui/pages/description_panel.hh
firmware/src/gui/pages/jackmaps.hh
firmware/src/gui/pages/main_menu.hh
firmware/src/gui/pages/patch_selector.hh
firmware/src/gui/pages/patch_view.hh
firmware/src/gui/pages/patch_view_settings_menu.hh
firmware/src/gui/pages/prefs_tab.hh
firmware/src/gui/slsexport/CMakeLists.txt
firmware/src/gui/slsexport/meta5/screens/ui_MainMenu.c
firmware/src/gui/slsexport/meta5/screens/ui_PatchSelectorPage.c
firmware/src/gui/slsexport/meta5/screens/ui_PatchViewPage.c
firmware/src/gui/slsexport/meta5/screens/ui_SystemMenu.c
firmware/src/gui/slsexport/meta5/ui.c
firmware/src/gui/slsexport/meta5/ui.h
firmware/src/gui/slsexport/prefs_pane_patch_suggested_audio.cc
firmware/src/gui/slsexport/prefs_pane_patch_suggested_audio.hh
firmware/src/gui/slsexport/ui_local.cc
firmware/src/gui/slsexport/ui_local.h
firmware/src/gui/styles.hh
firmware/src/gui/ui.hh
firmware/src/patch_play/patch_playloader.hh
firmware/src/user_settings/patch_suggested_audio_settings.hh
firmware/src/user_settings/settings.hh
firmware/src/user_settings/settings_parse.cc
firmware/src/user_settings/settings_serialize.cc
firmware/src/user_settings/view_settings.hh
firmware/tests/patch_player_tests.cc
firmware/tests/settings_parse_tests.cc
simulator/src/ui.cc

This PR adds two fields to the patch file format:
- `suggested_samplerate`
- `suggested_blocksize`
These can be set to any valid sample rate or block size, or to 0.
When a patch file is loaded, the audio settings will be automatically changed to those found in the patch file. If the field is 0 or missing, the audio setting won't be changed.
Since the sample rate and block size can now change dynamically without the user explicitly going the Prefs page, it's handy to display the current SR/BS at the top of the screen. Two new display options are added:
- `Show audio settings`: displays the current samplerate and blocksize next to the cpu load (`68% 48k/128`)
- `Keep load meter on top`: Puts the cpu load meter on top of the patch as you scroll through modules
This also adds two user …

Patch file can override audio settings
